config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  root 'dashboard#home'
  get 'week_day_menu' => 'dashboard#week_day_menu'

  resources :orders

  namespace :api, defaults: { format: :json } do
    resources :orders, only: :index
    resources :sessions, only: [:create, :destroy]
    resources :users, only: :show
  end

  get '*path' => redirect('/')
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, only: [:week_day_menu]

  def home
  end

  def week_day_menu
    @first_day = Date.today.at_beginning_of_week
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.slim
.container.
  .jumbotron
    h1 Welcome To Moscow Lunch Group

app/views/dashboard/home.slim
h1 Hi

app/views/dashboard/week_day_menu.html.slim
.row
  h1.text-center 
    = current_user.name.capitalize
  hr

.row
  .center
    - for i in 0..6
      - current_day = @first_day + i.days
      = link_to orders_path( date: current_day.strftime("%d-%m-%Y")) do
        .col-md-2
          .panel.panel-success
            .panel-heading
              .panel-title.title
                = current_day.strftime("%d.%m.%y")
            .panel-body{ class="#{'today' if current_day == Date.today}"}
              = current_day.strftime("%A")

app/views/dashboard/week_day_menu.slim
.row
  / - if current_user.has_role? :admin
  h1.text-center = current_user.name
  hr

.row
  - for i in 0..4
    .col-md-2{ class="col-md-offset-1" if i == 0 }
      = link_to (@first_day + i.days).strftime("%A %d.%m.%y"), "#"